name: AwesomeBans
main: net.somethingsuperawesome.awesomebans.AwesomeBans
version: Beta 0.11
author: Captain Awesome
commands:
   warn:
      usage: /<command> <player> <reason>
   check:
      usage: /<command> <player>
   checkdetail:
      usage: /<command> <record id>  
   ban:
      usage: /<command> <player> <duration - ex 1h5m> <reason>
   mute:
      usage: /<command> <player> <duration - ex 1h5m> <reason>
   unban:
      usage: /<command> <player>
   unmute:
      usage: /<command> <player>
   addlives:
      usage: /<command> <player> <amount>
   kick:
      usage: /<command> <player> <reason>
   importfc:
      usage: /<command>
   awesomebans:
      usage: /<command>
depend: [SQLibrary]